# Generated by Django 5.0.4 on 2024-04-10 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('countanswers', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profiles')),
                ('tag_id', models.ManyToManyField(to='app.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('right', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profiles')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Likeanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.BooleanField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.answers')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profiles')),
            ],
            options={
                'unique_together': {('answer_id', 'profile_id')},
            },
        ),
        migrations.CreateModel(
            name='Likequestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.BooleanField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profiles')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.questions')),
            ],
            options={
                'unique_together': {('question_id', 'profile_id')},
            },
        ),
    ]
